apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
  # Oder type: NodePort, um einen Port auf dem Host direkt freizugeben.
  # Oder Ingress nutzen, siehe unten.