services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: habitsdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
