apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoidnVsbmVyaXVzIiwicGFzc3dvcmQiOiJnaHBfSkc5M0Q4VWV1c3N3UGZNUDY0RHVRVnlFd1FpcmJKNGFkTzJBIiwiYXV0aCI6ImRuVnNibVZ5YVhWek9tZG9jRjlLUnprelJEaFZaWFZ6YzNkUVprMVFOalJFZFZGV2VVVjNVV2x5WWtvMFlXUlBNa0U9In19fQ==
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson