# iac/kubernetes/kustomization.yaml

# Auflistung aller Kubernetes-Ressourcen (Deployments, Services, Secrets, etc.),
# die von Kustomize verwaltet werden sollen.
# Diese Pfade sind relativ zum Ort dieser kustomization.yaml Datei.
resources:
  - postgres/secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - backend/service.yaml
  - backend/deployment.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - ghcr-secret.yaml
  - nginx/service.yaml
  - nginx/deployment.yaml

# Optional: Um die Replikat-Anzahl zu überschreiben, ohne die Deployment-Datei zu ändern.
# Du hast 2 Replikate für Backend und 4 für Frontend in deinen Deployments.
# Dies wäre nützlich, wenn du z.B. nur 1 Replikat für eine bestimmte Umgebung willst.
# replicas:
#   - name: backend-app
#     count: 2
#   - name: frontend-app
#     count: 4

# Optional: Image-Overlays (sehr nützlich, um Images zu aktualisieren!)
# Wenn du die Image-Tags aktualisieren musst, kannst du dies hier tun,
# anstatt direkt die Deployment-Dateien zu ändern.
# Kubernetes wird dann ein Rolling Update auslösen.
#images:
#  - name: disziplin-backend
#    newName: localhost:5000/disziplin-backend
 #   newTag: latest
 # - name: disziplin-frontend
 #   newName: localhost:5000/disziplin-frontend
 #   newTag: latest
