apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData: # Besser stringData für Klartext in YAML (wird base64-kodiert beim Apply)
  username: "appuser"
  password: "secret"