apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 2 # <-- Hier sind deine 2 Replikate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 'ghcr.io/vulnerius/disziplin/disziplin-backend:5d925e21e60b13bed83b984c23255a09ff703b9f'
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: postgres-db-service # Name des PostgreSQL Service
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
      imagePullSecrets:
        - name: ghcr-secret
