apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-deployment
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy-container
          image: ghcr.io/vulnerius/disziplin/nginx:18199b7421c78819c0e8a3762b9de5bb5305f19f
          ports:
            - containerPort: 80
            - containerPort: 443 # Wenn du HTTPS planst
      imagePullSecrets:
        - name: ghcr-secret
