apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-deployment
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy-container
          image: ghcr.io/vulnerius/disziplin/nginx:0c0fd155cc7fd5a801f21867bbb3abceef9f3f2a
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: "/etc/nginx/certs"
              name: tls-cert
              readOnly: true
      volumes:
        - name: tls-cert
          secret:
            secretName: disziplin-tls-secret
      imagePullSecrets:
        - name: ghcr-secret
